# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 388686baa31d0aa6470a07864c4697e9206c9f5765d627c73088781d1227acf8e6abfea33bdcb1cc390841300d0fe80b9ab0f751e211ccd9dc2d33b62aec1652

test:
  secret_key_base: dedb6e887460b1e578052d96a0caa2ad2d7ecd72e56de8c8773288c992e2016e03f62c59f8a9b42c522ab0d6d1391bfc3c1657c20bb82e721fccebe07d2f202e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
